//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxForTj.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ID { get; set; }
        public string A_Name { get; set; }
        public string A_PinYinJM { get; set; }
        public Nullable<int> A_IsUnderLine { get; set; }
        public Nullable<int> A_UnderLineCHSNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
