//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxForTj.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Config
    {
        public int ID { get; set; }
        public string ImageUrl { get; set; }
        public string TextTitle { get; set; }
        public string TextContent { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> SexType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string BianMa { get; set; }
        public string Sort { get; set; }
        public string FromPage { get; set; }
        public string CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
