//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxForTj.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiJianB
    {
        public string TiJianLSH { get; set; }
        public string YuYueLSH { get; set; }
        public string TiJianH { get; set; }
        public string GuiDangH { get; set; }
        public string CiKaLBBM { get; set; }
        public string CiKaLBMC { get; set; }
        public string XingMing { get; set; }
        public string XingBie { get; set; }
        public Nullable<decimal> NianLing { get; set; }
        public string ChuShenRQ { get; set; }
        public string HunYinZK { get; set; }
        public string YouXiaoZJ { get; set; }
        public string LianXiDH { get; set; }
        public string WenHuanCD { get; set; }
        public string JiGuan { get; set; }
        public string JiaTingDZ { get; set; }
        public string MinZu { get; set; }
        public string GongZuoDW { get; set; }
        public string ZhiYe { get; set; }
        public string DianZiYJ { get; set; }
        public string BeiZhu { get; set; }
        public string ZongGongL { get; set; }
        public string WaiBuGH { get; set; }
        public string BeiYong1 { get; set; }
        public string BeiYong2 { get; set; }
        public string WeiHaiYS { get; set; }
        public string ZaiGangLX { get; set; }
        public string JieHaiGL { get; set; }
        public string YuJianRQ { get; set; }
        public string BuMen { get; set; }
        public string ZaiZhiQK { get; set; }
        public string FuKeBZ { get; set; }
        public string FenZu { get; set; }
        public string TiJianLB { get; set; }
        public string JianChaLXBM { get; set; }
        public string JianChaLXMC { get; set; }
        public string ZhiYeBDXBM { get; set; }
        public string ZhiYeBDXMC { get; set; }
        public string YuDingTJRQ { get; set; }
        public string FenZuMC { get; set; }
        public string TiJianRQ { get; set; }
        public string DengJiRQ { get; set; }
        public string JieDaiGH { get; set; }
        public string JieDaiXM { get; set; }
        public string DanWeiBM { get; set; }
        public string DanWeiMC { get; set; }
        public string TaoCanBM { get; set; }
        public string TaoCanMC { get; set; }
        public string TaoCanMC_N { get; set; }
        public string DanWeiTCBM { get; set; }
        public string DanWeiTCMC { get; set; }
        public Nullable<decimal> TaoCanJE { get; set; }
        public Nullable<decimal> ZheKouL { get; set; }
        public Nullable<decimal> TaoCanZK { get; set; }
        public Nullable<decimal> YingFuJE { get; set; }
        public Nullable<decimal> ZongJinE { get; set; }
        public string TiJianJSRGH { get; set; }
        public string TiJianJSRXM { get; set; }
        public string ShiFouZJHZ { get; set; }
        public string ZhuSuTS { get; set; }
        public string ShiFouYZJ { get; set; }
        public string ChuangWeiH { get; set; }
        public string DaYinBZ { get; set; }
        public string ZongJianYSGH { get; set; }
        public string ZongJianYSXM { get; set; }
        public string ZongJianRQ { get; set; }
        public string ZongJie { get; set; }
        public string ZhenDuan { get; set; }
        public string YiShengJY { get; set; }
        public string MiaoShuJQ { get; set; }
        public string FuJianRQ { get; set; }
        public string FuJianTZRQ { get; set; }
        public string FuJianYY { get; set; }
        public string BiaoZhi { get; set; }
        public Nullable<int> Statue { get; set; }
        public string FaBaoGRQ { get; set; }
        public string FaBaoGFS { get; set; }
        public string JieSuanBH { get; set; }
        public string JieSuanRQ { get; set; }
        public string JieSuanBZ { get; set; }
        public string ShiFouFF { get; set; }
        public string FuFeiRQ { get; set; }
        public Nullable<decimal> XiuGaiBZ { get; set; }
        public string ShenGao { get; set; }
        public string TiZhong { get; set; }
        public string XueYa { get; set; }
        public string MaiBo { get; set; }
        public string QueRenRQ { get; set; }
        public string QuerenR { get; set; }
        public string CaoZuoYGH { get; set; }
        public string CaoZuoYXM { get; set; }
        public string ShenHeYSGH { get; set; }
        public string ShenHeYSXM { get; set; }
        public string LeiBieBM { get; set; }
        public string LeiBieMC { get; set; }
        public string ZYB_JieGuo { get; set; }
        public string ZYB_YiJian { get; set; }
        public string ZYB_JianYi { get; set; }
        public string ZYB_DingXing { get; set; }
        public string ZYB_ZhenDuan { get; set; }
        public Nullable<int> ShanChuBZ { get; set; }
        public byte[] Image { get; set; }
        public string ClientEdit { get; set; }
        public Nullable<int> CheckBZ { get; set; }
        public string SCBH { get; set; }
        public string FuJianH { get; set; }
        public string FuJianXM { get; set; }
        public Nullable<int> renyuanlsh { get; set; }
        public string FenPeiBZ { get; set; }
        public string XingMing_ENG { get; set; }
        public string ZhengJianLX { get; set; }
        public string GuoJi { get; set; }
        public string QianWangGJ { get; set; }
        public Nullable<decimal> JieZhongXMJE { get; set; }
        public Nullable<int> TiJianCS { get; set; }
        public string JingNW { get; set; }
        public string FaZhengJG { get; set; }
        public string TiJianJL { get; set; }
        public string ChuRuJLX { get; set; }
        public string ChuShengD { get; set; }
        public string TMJCDSFYDY { get; set; }
        public string TMJCDDYSJ { get; set; }
        public string TMJCDDYRY { get; set; }
        public string ZYB_QiTaJG { get; set; }
        public Nullable<int> BaoGaoDYCS { get; set; }
        public string BaoGaoJJBZ { get; set; }
        public string JiaoJieZT { get; set; }
        public string selfkey { get; set; }
        public Nullable<decimal> ZengJiaZKHJE { get; set; }
        public Nullable<decimal> ZengJiaJE { get; set; }
        public Nullable<decimal> TaoCanZKHJE { get; set; }
        public Nullable<decimal> TaoCanZJE { get; set; }
        public string ZuiHouXGRQ { get; set; }
        public string ZuiHouXGGH { get; set; }
        public string ZuiHouXGXM { get; set; }
        public string SFSFHDY { get; set; }
        public Nullable<int> GeRenJSZT { get; set; }
        public Nullable<int> DW_JSZT { get; set; }
        public Nullable<decimal> JieSuanJE_GR { get; set; }
        public Nullable<decimal> JieSuanJE_DW { get; set; }
        public string JieSuanBH_GR { get; set; }
        public string JieSuanBH_DW { get; set; }
        public string TJDYDSFYDY { get; set; }
        public string TJDYDDYSJ { get; set; }
        public string TJDYDDYRY { get; set; }
        public Nullable<decimal> DanWeiDE { get; set; }
        public string JieSuanRQ_GR { get; set; }
        public string JieSuanRQ_DW { get; set; }
        public Nullable<decimal> WFJE_GR { get; set; }
        public Nullable<decimal> WFJE_DW { get; set; }
        public Nullable<decimal> YFJE_GR { get; set; }
        public Nullable<decimal> YFJE_DW { get; set; }
        public string LaiJianRQ { get; set; }
        public string BCZFBZ { get; set; }
        public Nullable<int> ChoseTJ { get; set; }
        public int YangXingBZ { get; set; }
        public string teshusx { get; set; }
        public string teshubz { get; set; }
        public decimal GRJSJE { get; set; }
        public decimal DWJSJE { get; set; }
    }
}
